export const US_STATES = [
    { name: 'Alabama', abbreviation: 'AL' },
    { name: 'Alaska', abbreviation: 'AK' },
    { name: 'Arizona', abbreviation: 'AZ' },
    { name: 'Arkansas', abbreviation: 'AR' },
    { name: 'California', abbreviation: 'CA' },
    { name: 'Colorado', abbreviation: 'CO' },
    { name: 'Connecticut', abbreviation: 'CT' },
    { name: 'Delaware', abbreviation: 'DE' },
    { name: 'Florida', abbreviation: 'FL' },
    { name: 'Georgia', abbreviation: 'GA' },
    { name: 'Hawaii', abbreviation: 'HI' },
    { name: 'Idaho', abbreviation: 'ID' },
    { name: 'Illinois', abbreviation: 'IL' },
    { name: 'Indiana', abbreviation: 'IN' },
    { name: 'Iowa', abbreviation: 'IA' },
    { name: 'Kansas', abbreviation: 'KS' },
    { name: 'Kentucky', abbreviation: 'KY' },
    { name: 'Louisiana', abbreviation: 'LA' },
    { name: 'Maine', abbreviation: 'ME' },
    { name: 'Maryland', abbreviation: 'MD' },
    { name: 'Massachusetts', abbreviation: 'MA' },
    { name: 'Michigan', abbreviation: 'MI' },
    { name: 'Minnesota', abbreviation: 'MN' },
    { name: 'Mississippi', abbreviation: 'MS' },
    { name: 'Missouri', abbreviation: 'MO' },
    { name: 'Montana', abbreviation: 'MT' },
    { name: 'Nebraska', abbreviation: 'NE' },
    { name: 'Nevada', abbreviation: 'NV' },
    { name: 'New Hampshire', abbreviation: 'NH' },
    { name: 'New Jersey', abbreviation: 'NJ' },
    { name: 'New Mexico', abbreviation: 'NM' },
    { name: 'New York', abbreviation: 'NY' },
    { name: 'North Carolina', abbreviation: 'NC' },
    { name: 'North Dakota', abbreviation: 'ND' },
    { name: 'Ohio', abbreviation: 'OH' },
    { name: 'Oklahoma', abbreviation: 'OK' },
    { name: 'Oregon', abbreviation: 'OR' },
    { name: 'Pennsylvania', abbreviation: 'PA' },
    { name: 'Rhode Island', abbreviation: 'RI' },
    { name: 'South Carolina', abbreviation: 'SC' },
    { name: 'South Dakota', abbreviation: 'SD' },
    { name: 'Tennessee', abbreviation: 'TN' },
    { name: 'Texas', abbreviation: 'TX' },
    { name: 'Utah', abbreviation: 'UT' },
    { name: 'Vermont', abbreviation: 'VT' },
    { name: 'Virginia', abbreviation: 'VA' },
    { name: 'Washington', abbreviation: 'WA' },
    { name: 'West Virginia', abbreviation: 'WV' },
    { name: 'Wisconsin', abbreviation: 'WI' },
    { name: 'Wyoming', abbreviation: 'WY' },
    { name: 'District of Columbia', abbreviation: 'DC' },
    { name: 'American Samoa', abbreviation: 'AS' },
    { name: 'Guam', abbreviation: 'GU' },
    { name: 'Northern Mariana Islands', abbreviation: 'MP' },
    { name: 'Puerto Rico', abbreviation: 'PR' },
    { name: 'United States Minor Outlying Islands', abbreviation: 'UM' },
    { name: 'Virgin Islands, U.S.', abbreviation: 'VI' },
];

export const COMPANY_LICENSE_TYPE = [
    { name: 'Alarm Company', abbreviation: 'AC' },
    { name: 'Approved Trainer - PSO Curriculum', abbreviation: 'AT-PSO' },
    { name: 'Baton Training Facility', abbreviation: 'BTF' },
    { name: 'Firearm Training Facility', abbreviation: 'FTF' },
    { name: 'Locksmith Company', abbreviation: 'LC' },
    { name: 'Locksmith Employee', abbreviation: 'LE' },
    { name: 'Private Investigator Company', abbreviation: 'PIC' },
    { name: 'Private Security Operator', abbreviation: 'PSO' },
    { name: 'Repossession Agency', abbreviation: 'RA' },
];

export const GUARD_LICENSE_TYPE = [
    { name: 'Alarm Company Employee', abbreviation: 'ACE' },
    { name: 'Alarm Company Operator', abbreviation: 'ACO' },
    { name: 'Alarm Company Qualified Manager', abbreviation: 'ACQM' },
    { name: 'Baton Training Facility Instructor', abbreviation: 'BTFI' },
    { name: 'Company Principal', abbreviation: 'CP' },
    { name: 'Exposed Firearm Permit', abbreviation: 'EFP' },
    { name: 'Firearm Training Facility Instructor', abbreviation: 'FTFI' },
    { name: 'Locksmith Employee', abbreviation: 'LE' },
    { name: 'Private Investigator', abbreviation: 'PI' },
    { name: 'Private Investigator Qualified Manager', abbreviation: 'PIQM' },
    { name: 'Private Investigator Qualified Manager License', abbreviation: 'PIQML' },
    { name: 'Private Patrol Qualified Manager', abbreviation: 'PPQM' },
    { name: 'Proprietary Private Security Employer', abbreviation: 'PPSE' },
    { name: 'Proprietary Private Security Officer', abbreviation: 'PPSO' },
    { name: 'Repossession Agency Employee', abbreviation: 'RAE' },
    { name: 'Repossession Agency Qualified Manager', abbreviation: 'RAQM' },
];
